apiVersion: apps/v1
kind: Deployment
metadata:
  name: default-app
  labels:
    app.kubernetes.io/name: default-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: default-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: default-app
    spec:
      serviceAccountName: default-app-sa
      automountServiceAccountToken: true
      securityContext:
        runAsNonRoot: true
        runAsUser: 2001
        runAsGroup: 2001
      nodeSelector:
        kubernetes.io/os: linux
      containers:
        - name: default-app-ctr
          image: mmckernan/default-app:0.1.0
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          livenessProbe:
            httpGet:
              port: 8080
              path: /actuator/health
          readinessProbe:
            httpGet:
              port: 8080
              path: /actuator/health
          securityContext:
            privileged: false
            allowPrivilegeEscalation: false
