apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ingress-nginx
commonLabels:
  app.kubernetes.io/version: 0.1.0
resources:
  - deployment.yaml
  - service.yaml
  - service_account.yaml
