apiVersion: v1
kind: Service
metadata:
  name: default-service
  labels:
    app.kubernetes.io/name: default-app
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      name: http
  selector:
    app.kubernetes.io/name: default-app
